<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>MarcusRunge.AviationAgent.ConsoleApp</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../MarcusRunge.AviationAgent.AviationWeather/MarcusRunge.AviationAgent.AviationWeather.csproj" />
		<ProjectReference Include="../MarcusRunge.AviationAgent.Core/MarcusRunge.AviationAgent.Core.csproj" />
		<ProjectReference Include="../MarcusRunge.AviationAgent.OnnxRuntime/MarcusRunge.AviationAgent.OnnxRuntime.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>